name: Daily Bible Reminder

on:
  schedule:
    # Runs at 11:45 PM UTC (7:45 AM PHT) every day
    - cron: '45 23 * * *'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  send-daily-reminder:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Send daily Bible reminder
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        BOT_TIMEZONE: Asia/Manila
      run: |
        export TZ=Asia/Manila
        echo "🕘 Starting daily Bible reminder at $(date)"
        echo "🌐 UTC time: $(TZ=UTC date)"
        npm run schedule
        echo "✅ Daily Bible reminder completed at $(date)"
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Daily Bible reminder failed at $(TZ=Asia/Manila date)"
        echo "Check the logs above for error details"